---
- name: Check Facts
  hosts: debian
  tasks:
    - name: Assert that distribution is Debian
      ansible.builtin.assert:
        that:
          - ansible_facts['distribution'] == "Debian"

    - name: Assert that distribution version is 12
      ansible.builtin.assert:
        that:
          - ansible_facts['distribution_major_version'] | int == 12

    - name: Assert that connection user is ansible
      ansible.builtin.assert:
        that:
          - ansible_facts['user_id'] == "ansible"
