---
- name: SSH Configuration
  block:
    - name: Render SSH Banner
      become: true
      register: sshd_dropin_banner_result
      ansible.builtin.template:
        validate: /usr/sbin/sshd -t -f %s
        src: templates/banner.j2
        dest: /etc/ssh/sshd_config.d/10_banner.conf
        mode: '0644'
        owner: root
        group: root
        backup: true

    - name: Verify SSH Configuration
      become: true
      changed_when: sshd_dropin_banner_result is changed
      notify: Restart SSH
      ansible.builtin.command:
        cmd: /usr/sbin/sshd -t

  rescue:
    - name: Remove SSH Banner
      become: true
      when:
        - sshd_dropin_banner_result is changed
        - sshd_dropin_banner_result.backup_file is not defined
      ansible.builtin.file:
        path: /etc/ssh/sshd_config.d/10_banner.conf
        state: absent

    - name: Revert SSH Banner
      become: true
      when:
        - sshd_dropin_banner_result is changed
        - sshd_dropin_banner_result.backup_file is defined
      ansible.builtin.copy:
        src: "{{ sshd_dropin_banner_result.backup_file }}"
        dest: /etc/ssh/sshd_config.d/10_banner.conf
        remote_src: true
        mode: '0644'
        owner: root
        group: root

    - name: Explain SSH Banner Failure
      ansible.builtin.fail:
        msg: "{{ sshd_dropin_banner_result.stderr }}"

  always:
    - name: Find SSH Backup Files
      become: true
      register: sshd_dropin_backup_files
      ansible.builtin.find:
        paths: /etc/ssh/sshd_config.d/
        patterns: "10_banner.conf.*~"

    - name: Assert SSH Backup Files Listed
      ansible.builtin.assert:
        that:
          - sshd_dropin_backup_files.skipped_paths is defined
          - sshd_dropin_backup_files.skipped_paths | length == 0

    - name: Delete SSH Backup Files
      become: true
      loop: "{{ sshd_dropin_backup_files.files }}"
      when: sshd_dropin_backup_files.files is defined
      loop_control:
        label: "{{ item.path }}"
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent

- name: Find SSH Backup Files
  become: true
  register: sshd_dropin_backup_files
  ansible.builtin.find:
    paths: /etc/ssh/sshd_config.d/
    patterns: "10_banner.conf.*~"

- name: Assert no SSH Backup Files
  when: sshd_dropin_backup_files.files is defined
  ansible.builtin.assert:
    that:
      - sshd_dropin_backup_files.files | length == 0
      - sshd_dropin_backup_files.skipped_paths is defined
      - sshd_dropin_backup_files.skipped_paths | length == 0
